# fly.toml app configuration file generated for wandering-moon-6543 on 2023-05-01T00:53:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-full-stack-open-pokedex"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[build]

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[processes]
  app = "node app.js"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.script_checks]]
    command       = "/app/health_check.sh"
    grace_period  = "5s"
    interval      = "5s"
    restart_limit = 0
    timeout       = "1s"
